import Apartment from "./apartment";
import ApartmentBuilder from "./apartmentBuilder";

export default class ConcreteApartmentBuilder implements ApartmentBuilder{
    private rooms : number;
	private dinningRooms : number;
	private bathRooms : number;
	private laundry : number;
	private balcone : number;
    private price : number;

    
    constructor(){
        this.rooms = 0;
        this.dinningRooms = 0;
        this.bathRooms = 0;
        this.laundry = 0;
        this.balcone = 0;
        this.price = 0;
    }

    public getResult() : Apartment{
        return new Apartment(this.rooms,this.dinningRooms,this.bathRooms,this.laundry,this.balcone,this.price);
    }

    public buildRooms(amount : number) : void{
        this.rooms += amount;
    }
    public buildDinningRooms(amount : number) : void{
        this.dinningRooms += amount;        
    }
    public buildBathRooms(amount : number) : void{
        this.bathRooms += amount;
    }
    public buildLaundry(amount : number) : void{
        this.laundry += amount;
    }
    public buildBalcone(amount : number) : void{
        this.balcone += amount;
    }
    public setPrice(amount : number) : void{
        this.price = amount;        
    }

    //autogenerated functions -------------------------------------------------------------------------------------------------------
    public getRooms(): number {
        return this.rooms;
    }

    public setRooms(rooms: number): void {
        this.rooms = rooms;
    }

    public getDinningRooms(): number {
        return this.dinningRooms;
    }

    public setDinningRooms(dinningRooms: number): void {
        this.dinningRooms = dinningRooms;
    }

    public getBathRooms(): number {
        return this.bathRooms;
    }

    public setBathRooms(bathRooms: number): void {
        this.bathRooms = bathRooms;
    }

    public getLaundry(): number {
        return this.laundry;
    }

    public setLaundry(laundry: number): void {
        this.laundry = laundry;
    }

    public getBalcone(): number {
        return this.balcone;
    }

    public setBalcone(balcone: number): void {
        this.balcone = balcone;
    }

    public getPrice(): number {
        return this.price;
    }




}